### ISSUE TITLE
Toggle checkboxes

### ISSUE THREAD

**Issue by karimknaebel** [nguyenvukhang/nvim-toggler#6]
Is it possible to toggle `- [ ]` and `- [x]`?

**Comment by nguyenvukhang** [comment]
`- [ ]` and `- [x]` both have a space in-between. Currently, `nvim-toggler` makes use of a (custom) `<cword>` call to figure out what's the word the user is trying to toggle, so it won't be able to recognize these patterns properly.

I'll keep this issue open because this has been a problem to myself in the past and `nvim-toggler` sounds like a tool that should be able to deal with this.

Thanks for bringing this up!

**Comment by karimknaebel** [comment]
I thought so, just wanted to make sure. Thanks for clarifying :)

**Comment by jgollenz** [comment]
[vim-checkbox](https://github.com/jkramer/vim-checkbox) is basically grepping for the first checkbox in the line. Not perfect, but does the job.

**Comment by nguyenvukhang** [comment]
closed with https://github.com/nguyenvukhang/nvim-toggler/releases/tag/v0.3.0
